export const HEALTH_CHECK_TIMEOUT_MS = 8000;
export const HEALTH_CHECK_CONCURRENCY = 16;
export const PRELOAD_LIMIT = 10;
export const TOTAL_PLAYER_SLOTS = 11;
export const HOVER_PRELOAD_DELAY_MS = 300;
